name: Github Actions 실행하기

on:
  push:
    branches:
      - main

jobs:
  My-First-CICD-Job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-web
        run:  echo "This is the first cicd step"

      - name: multiple-lines
        run : |
          echo "line 1"
          echo "line 2"

      - name: Github variables 사용하기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY   

      - name : Github Secret 변수 사용하기
        run : |
          echo ${{ secrets.MY_ENV_NAME }}
          echo ${{ secrets.MY_ENV_PASSWORD }}       
